// Example of a macro that receives an expression as a parameter
macro_rules! pubsub_subscribe {
    ($topic:expr) => {
        pub fn subscribe_to_topic() {
            println!("Subscribed to topic: {}", $topic);
        }
    };
}

// Example of a macro that is expanded into a function
macro_rules! my_macro {
    () => {
        fn inner_function() {
            const VALUE: u32 = 42;

            // Print the value of the constant in the function
            println!("The value of the constant is: {}", VALUE);
        }

        // Call the inner function from the macro
        inner_function();
    };
}

fn second_function() {
    my_macro!();
}

pubsub_subscribe!("topic_1");
fn main() {
    // This function is generated by the macro
    subscribe_to_topic();

    second_function();
}
